language: node_js
node_js:
  - "10"
  - "12"
matrix:
    include:
      - os: linux
        env: DIST=--linux
      - os: windows
        env: DIST=--windows
      - os: osx
        env: DIST=--mac
script:
  - npm run test
  - npm run postinstall
  - npm run release-$DIST
